### ISSUE TITLE
Roslynpad suddenly stopped working [might be user error]

### ISSUE THREAD

**Issue by Kirides** [aelij/RoslynPad#390] opened 2021-05-05 06:53 UTC
**Describe the bug**

Using `net5.0` as target, Roslynpad prints Json error and written script is not properly executed.
It worked previously with `.NET Core 5.0.101`, since `.NET Core 5.0.201` neither one works (both are choosable)

`.NET Framework x86 / x64` does work.

```
JsonReaderException
Unexpected character encountered while parsing value: O. Path '', line 0, position 0.
```

**READ THIS**
----

There is a difference in how ProcessStartInfo works between .NET Framework and .NET Core.
Core defaults to `pi.UseShellExecute = false;` which causes the issue, while Framework used `UseShellExecute = true;`

Workaround: redirect stdout and stderr, so they don't print to the console by themselves.

**To Reproduce**

```cs
using System.Diagnostics;

void Run()
{
    var piGitCommit = new ProcessStartInfo("git");
    piGitCommit.WorkingDirectory = @"G:\Temp\demogit";

    var p = Process.Start(piGitCommit);
    p.WaitForExit();
    
    Console.WriteLine("Hello World!");
}
Run();
```

Seems to have something todo with the `Process.Start`, as regular prints work.
```cs
using System.Diagnostics;

void Run()
{    
    Console.WriteLine("Hello World!");
}
Run();
```

**Expected behavior**

see "Hello World!" being printed

**Version**
- OS: Windows 10 20H2 (19042.928)
- Build (or commit ID if built from source): 15.1

**Comment by aelij** [comment] 2021-07-10 06:39
Duplicate of #370

**Closed by aelij** 2021-07-10 06:39 UTC
