### ISSUE TITLE
output mandarin is garbled text

### ISSUE THREAD

**Issue by leejulee** [aelij/RoslynPad#274] opened 2019-05-02 05:27 UTC
Hi, 
Could you fix this problem?

- Code: `Console.WriteLine("台灣 (Taiwan)");`

- Output: ![Imgur](https://i.imgur.com/9NT10Jk.png)

- RoslynPad Version:14.1

Thank you.

**Comment by aelij** [comment] 2019-05-03 07:21
Duplicate of #256

**Closed by aelij** 2019-05-03 07:21 UTC
