### ISSUE TITLE
Program is not public, breaking XmlSerializer

### ISSUE THREAD

**Issue by w5l** [aelij/RoslynPad#387] opened 2021-03-02 11:28 UTC
**Describe the bug**

I want to use Roslynpad to test siome `XmlSerializer` code. `XmlSerializer` only serializes public types. When I create types in Roslynpad, they are not public, and the serializer throws. I guess, the program get wrapped in a main class which maybe isn't public?

**To Reproduce**

Open Roslynpad, execute following code:

```cs
using System.Xml.Serialization;
var xmlSerializer = new XmlSerializer(typeof(Test));
public class Test {}
```

This throws `InvalidOperationException`: "Program is inaccessible due to its protection level. Only public types can be processed.". Result is the same regardless of chosen framework.

**Expected behavior**

No exception 😉 

**Version**
- OS: Win10
- Build (or commit ID if built from source): 15.1

**Comment by aelij** [comment] 2021-03-02 11:30
Unfortunately it's out of my control
Duplicate of #275

**Closed by aelij** 2021-03-02 11:30 UTC

**Comment by w5l** [comment] 2021-03-02 11:36
Ah sorry, I checked the existing issues but used different search terms.
