### ISSUE TITLE
C# 9 support?

### ISSUE THREAD

**Issue by MarqueIV** [aelij/RoslynPad#385] opened 2021-01-30 00:08 UTC
**Describe the bug**
Trying to use C#9 features but not having any luck.
**To Reproduce**
Try using Record types, init-only properties, etc., but they won't compile.
**Expected behavior**
I'd expect that I can use them.
**Version**
15.1
- OS:
Win10
- Build (or commit ID if built from source):

**Comment by aelij** [comment] 2021-01-30 08:15
Duplicate of #373

**Closed by aelij** 2021-01-30 08:15 UTC
