### ISSUE TITLE
Documents not saving when switching tabs!!

### ISSUE THREAD

**Issue by MarqueIV** [aelij/RoslynPad#325] opened 2020-01-25 18:11 UTC
Ok, this *may* have been recently fixed as I haven't been able to repro it in the last couple days, but on the flip-side, I don't remember the exact steps that caused it.  It seems in certain scenarios, if you've edited a file, then switched tabs or documents, then came back to the original tab, all of your recent changes were lost, reverting back to the last-saved version.

Again, I haven't seen this in the past couple of days, but I also don't see any commits that reference this, so I figured better safe than sorry to call it out.  If I do manage to repro it again, I'll report the exact steps as I'm watching out for it eagle-eyed at present as it was the cause of losing two hours of work a couple weeks ago that ruined my night! :)

**Comment by aelij** [comment] 2020-01-27 04:24
Duplicate of #316 (same root cause)

**Closed by aelij** 2020-01-27 04:24 UTC

**Comment by MarqueIV** [comment] 2020-01-27 04:31
👍🏻
