### ISSUE TITLE
Limit ResultObject recursion by tracking references

### ISSUE THREAD

**Issue by ohadschn** [aelij/RoslynPad#190] opened 2018-03-18 23:08 UTC
When I run a snippet with `EqualityComparer<byte>.Default.GetType()` RP hangs. 
Tried restarting, no change.

**Comment by aelij** [comment] 2018-03-19 09:32
It's probably because `Type` has a huge graph (that backtracks in a lot of places). We really should implement something that checks if a reference already appeared and stop serializing it (in `ResultObject`). Care to submit a PR? :)

Meanwhile, you can circumvent this by limiting the dump depth:

```
EqualityComparer<byte>.Default.GetType().Dump(maxDepth: 3);
```

(Note the `;` at the end - if it's missing, `Dump` would work, but the program would still get stuck since RP also dumps the last expression. A semicolon makes it a statement, so no extra dump.)

**Comment by aelij** [comment] 2018-03-25 19:05
A simple `HashSet<object>` with a `ReferenceEqualityComparer` should do the trick :)

**Comment by gilessmart** [comment] 2018-08-10 17:40
I think it'd be a shame for the whole object graph not to be available to browse. It can be really useful to navigate an object's members to learn how to use a type, so if the list of members can't be trusted then arguably something's been lost.

So I was thinking it might be better if RoslynPad could process just the members that are currently visible on the UI, then process more as they're needed as the user explored the object graph. Unfortunately I've not been able to work out a way to do this that I'd be confident about. I think you'd need to store the actual object being Dump()'d, but (if I've understood correctly) these objects are created in a separate 'host' process and that means the UI can't have direct access to them - hence why they're being serialized before being sent back to the UI. You could store these objects in the host process and query them over RPC maybe, but I'm not sure that's a good idea..

I might be able to have a go at what @aelij has suggested though.

Maybe we could take that one step further and replace the duplicate members with a placeholder indicating that a member should be present at this location in the tree and where the member being duplicated can be found? You could imagine in future that the UI could substitute the original object for the placeholder on demand achieving the appearance that the object is complete.

Another consideration might be that if the `ResultObject` is constructed depth-first (I _think_ it is..) then you could end up with output where some member is buried very deep in the tree, and placeholders appear closer to the root. This could be mitigated by adding & removing items from the HashSet as you recurse down & back up through the object you're converting to a `ResultObject` though.

I think I've convinced myself I'll have a go!

Any thoughts welcome.

**Comment by aelij** [comment] 2018-08-10 18:15
@gilessmart The thing is, it works by design since I wanted snapshot semantics. If you dump the same object twice after modifying it, you'll be able to see the differences.

You're welcome to give my suggestion a go :)

**Comment by gilessmart** [comment] 2018-08-12 10:48
Ah, thanks @aelij - that makes sense.

**Comment by aelij** [comment] 2018-12-08 15:31
After some investigation I'm closing this as no-fix. Marking repeated objects makes for a bad UX IMO.

**Closed by aelij** 2018-12-08 15:31 UTC
Labels: bug
