### ISSUE TITLE
Console and Dump (of 14.1) dislays invalid caharcters of strings with non ASCII code pages?

### ISSUE THREAD

**Issue by mshakurov** [aelij/RoslynPad#293] opened 2019-07-06 12:21 UTC
"Russian Тру Ля Ля".Dump();
displays:
Russian РўСЂСѓ Р›СЏ Р›СЏ

![DisplayError](https://user-images.githubusercontent.com/5284014/60756078-a67afc00-a001-11e9-9e37-1daec01d642f.png)

**Comment by aelij** [comment] 2019-07-06 12:29
Duplicate of #256

**Closed by aelij** 2019-07-06 12:29 UTC
