### ISSUE TITLE
how to edit as cs file with RoslynCodeEditor

### ISSUE THREAD

**Issue by BillShawn** [aelij/RoslynPad#307] opened 2019-10-22 14:07 UTC
At first, thank you very much for your sharing. My project uses the RoslynCodeEditor control, but it always works in *. CSX file. I would like it to work in *.CS file. How can I implement it through this control?

**Comment by aelij** [comment] 2019-10-23 03:55
Duplicate of #150 
See last comment https://github.com/aelij/RoslynPad/issues/150#issuecomment-341541762

**Closed by aelij** 2019-10-23 03:55 UTC

**Comment by BillShawn** [comment] 2019-10-23 06:19
I've tried, but failed. The example of RoslynCodeeEditor can't work normally. What I'm trying to do now is to copy the code of the example and regenerate it. But there are many problems, so now I can't even locate the problem. Can you provide me a download link for the normal operation of the example. I've tried to download many versions of RoslynPad, but all RoslynPadReplSample can't work.

**Comment by BillShawn** [comment] 2019-10-23 06:19
I've tried, but failed. The example of RoslynCodeeEditor can't work normally. What I'm trying to do now is to copy the code of the example and regenerate it. But there are many problems, so now I can't even locate the problem. Can you provide me a download link for the normal operation of the example. I've tried to download many versions of RoslynPad, but all RoslynPadReplSample can't work.
