### ISSUE TITLE
Error when running RoslynPad 14.1 on MacOS

### ISSUE THREAD

**Issue by mviegas** [aelij/RoslynPad#271] opened 2019-04-30 14:12 UTC
Hi!

When I try to run the .net Core version for Mac/Linux as described in instructions, I get the following error.

```
dotnet RoslynPad.dll
Error:
  An assembly specified in the application dependencies manifest (RoslynPad.deps.json) was not found:
    package: 'System.Drawing.Common', version: '4.5.0'
    path: 'runtimes/unix/lib/netcoreapp2.0/System.Drawing.Common.dll'
```

**Comment by aelij** [comment] 2019-05-03 07:23
Duplicate of #249 - you're missing some files when unzipping

**Closed by aelij** 2019-05-03 07:23 UTC
