### ISSUE TITLE
Last line in the output not getting printed to console

### ISSUE THREAD

**Issue by subhendubharti** [aelij/RoslynPad#280] opened 2019-05-08 08:01 UTC
The count of the items in result list is 4.
But when printing all the items in the list, only three are getting printed to console.
The last item is not getting printed to the console.
Refer to the screenshot:
![image](https://user-images.githubusercontent.com/10671681/57359535-88298900-7195-11e9-87d0-3005db7d4d69.png)

**Comment by aelij** [comment] 2019-05-09 10:54
Please provide the code as text

**Comment by subhendubharti** [comment] 2019-05-13 11:33
// This is the code I was trying to execute. The Result count is 4, but only 3 items are printed.
var list = new List<float>(){
6759.5f,1000f,2000f,34567,6754,67500f,6750
};
var s = 675f;
//foreach (var item in list)
//{
////    Console.WriteLine(item.ToString() + ":  " + item.ToString().Substring(0, 3) + ":  " + item.ToString().Substring(0, 3).Length);
//}
var result = list.Where(x => x.ToString().Substring(0, 3).Equals("675")).ToList();
Console.WriteLine("Result count: " + result.Count);
foreach (var item in result)
{
    Console.WriteLine(item);
}

**Comment by aelij** [comment] 2019-07-05 08:36
I believe this is a duplicate of #253. Let me know if this behavior repeats in the next release.

**Closed by aelij** 2019-07-05 08:36 UTC
