### ISSUE TITLE
Orphan execution host processes

### ISSUE THREAD

**Issue by aelij** [aelij/RoslynPad#25] opened 2016-06-14 06:49 UTC

**Comment by modulexcite** [comment] 2016-06-22 12:55
hi,

Thank you for the application, Keep up the great work. 
This is just to confirm that I too noticed a lot of orphaned host processes still running in the background after exiting the application. They end up taking a huge amount of resources at least on my machine which tends to push me towards using scriptcs.

**Comment by modulexcite** [comment] 2016-07-20 19:26
the issue is still persistent in version 0.9; I have the "RoslynPad.Host32.exe" process still running in the background after exiting from RoslynPad.

**Comment by aelij** [comment] 2016-07-21 06:39
@modulexcite 

Hmm, that's not what this issue was about actually. What I've seen happen was when you closed a tab on RoslynPad, sometimes a host process would remain. That was fixed.

I've never seen what you're describing - I'm using the Windows [CreateJobObject](https://msdn.microsoft.com/en-us/library/windows/desktop/ms682409(v=vs.85).aspx) to associate child processes with the parent process, and the OS is supposed to kill all child processes automatically when the parent terminates (or even killed).

What OS version are you using?

**Comment by modulexcite** [comment] 2016-07-21 14:00
oh, sorry about that then. Perhaps I should open a new issue.
I'm using Windows 7 SP1 Professional and using RoslynPad version 0.9, below is a screen capture of the said issue. 
Thank you for your response.

![roslynpad-bug-orphaned-host-processes](https://cloud.githubusercontent.com/assets/12729391/17025417/c4354484-4f29-11e6-9c0f-9b8e75739665.gif)

**Comment by aelij** [comment] 2016-07-21 16:46
It's fine, you don't need to open another issue.

I really don't know why this is happening. I'll try to investigate.

**Comment by modulexcite** [comment] 2016-07-21 17:00
Thank you




On Thu, Jul 21, 2016 at 12:46 PM -0400, "Eli Arbel" <notifications@github.com> wrote:












Reopened #25.

**Comment by IanYates** [comment] 2016-07-24 14:03
@modulexcite - can you run Sysinternals Process Explorer, have its file menu "show processes for all users" (you'll get a UAC prompt) and then inspect the properties of the RoslynPad processes.  There's a "Job" tab in the properties window which should show which processes are in the job.  That might help @aelij with tracking down your issue as it'll show if there's a problem with gathering the processes into a single job in the first place or perhaps there's something else afoot.

(just my 2c as an interested bystander).

**Comment by aelij** [comment] 2016-07-24 14:04
Thanks @IanYates, that's a great idea.

**Comment by modulexcite** [comment] 2016-07-25 09:29
Thanks for the suggestion @IanYates.
Attached are the screenshots of both the parent and the child processes; however I don't see anything unusual in the "Jobs" tab and I'm entirely sure what they mean. Perhaps @aelij can shed some light on this or use it for troubleshooting the issue at hand.

**Parent "RoslynPad.exe" process:**
![procexp64_roslynpad exe7588_properties_2016-07-25_05-25-43](https://cloud.githubusercontent.com/assets/12729391/17096681/9b8adc9a-5228-11e6-8838-458de58d1912.png)


**Child "RoslynPad.Host32.exe" process:** 
![procexp64_process_explorer_-_sysinternals_www sysinternals _2016-07-25_05-26-21](https://cloud.githubusercontent.com/assets/12729391/17096693/a8222e7c-5228-11e6-8941-753ebffe1fdc.png)


![procexp64_roslynpad host32 exe7976_properties_2016-07-25_05-26-52](https://cloud.githubusercontent.com/assets/12729391/17096708/b8f20614-5228-11e6-8b3c-2de1b04f5a4a.png)

**Comment by aelij** [comment] 2016-07-25 10:15
Very weird. Everything looks fine. @IanYates do you have any insights?

@modulexcite What these job objects do is associate a few processes together. It can be configured so when the last handle of the job is closed, all the processes are terminated. And in RoslynPad, the only open handle is in the main process.

I'll try closing the handle explicitly on exit, see if that helps.

**Comment by modulexcite** [comment] 2016-07-25 10:33
Thanks @aelij.
Maybe this has something to do with settings on my machine considering nobody else has reported this issue. I'll check if DebugDiag will provide any insight into what's happening.

**Comment by aelij** [comment] 2016-07-25 10:45
If you're in the mood, could you add modify `MainViewModel.OnExit` to this and see if it makes any difference?

```
public async Task OnExit()
{
	ChildProcessManager.Dispose();
	await AutoSaveOpenDocuments().ConfigureAwait(false);
}
```

**Comment by modulexcite** [comment] 2016-07-25 10:50
sure, will give it a try and let you know.

**Comment by modulexcite** [comment] 2016-07-25 11:22
after modifying MainViewModel.OnExit method with your code, it's killing the process when I'm debugging the code from Visual Studio but not if I launch RoslyPad independently. 
I've also tried attaching it to RoslynPad from Visual Studio but that's not killing the left over host process either which is weird.

**Comment by aelij** [comment] 2016-07-25 11:23
What happens if you run RP (without a debugger) and kill it from the task manager?

**Comment by modulexcite** [comment] 2016-07-25 11:34
It just kills the RP process and leaves behind the ".host32" process, sorry for the trouble. I'm sure you have better things to do than just fix this one problem nobody else has reported.

___________________________
Thanks.




On Mon, Jul 25, 2016 at 7:23 AM -0400, "Eli Arbel" <notifications@github.com> wrote:












What happens if you run RP (without a debugger) and kill it from the task manager?

**Comment by IanYates** [comment] 2016-07-25 11:59
Checking the low-hanging fruit firstly...

* Do you have an anti-virus scanner running?
* Are you using files in a folder managed by DropBox, OneDrive, etc?

(I'm trying to think of some external process that might keep things alive due to file handles or other interceptions)

I've not read the code, but what @aelij says sounds right - there's some sort of handle hanging around.

In Process Explorer, out of the properties window (back on the main screen), you can display a list of handles held by a process or a list of libraries loaded in to the process.  What handles do you have open in each process, and what handles remain after you quit RP?  You'll see things like file handles, mutexes, etc.

**Comment by modulexcite** [comment] 2016-07-25 12:48
I do have an anti-virus scanner running, it's McAfee and I can't disable that as this is my work laptop. I also have OneDrive, TortoiseSVN running in Windows explorer which I can control. However none of these processes have any handles on "RP.Host32.exe" process.

After closing RP, I can verify that the following processes still have handles on "Host32" process.

1. system
2. csrss
3. svchost
4. ccmexec

Let me know if you need more information.

**RoslynPad.exe Handles:**
![procexp64_process_explorer_search_2016-07-25_08-33-22](https://cloud.githubusercontent.com/assets/12729391/17101605/8cb2ae08-5243-11e6-88d4-77f429ec4ff1.png)


**RoslynPad.Host32.exe Handles prior to exiting RoslynPad:**
![procexp64_process_explorer_search_2016-07-25_08-32-05](https://cloud.githubusercontent.com/assets/12729391/17101637/a9c2878e-5243-11e6-9bd5-b16778293070.png)



**RoslynPad.Host32.exe Handles after exiting RoslynPad:**
![procexp64_process_explorer_search_2016-07-25_08-37-53](https://cloud.githubusercontent.com/assets/12729391/17101647/ae3ed880-5243-11e6-87af-5946a29b249c.png)

**Comment by IanYates** [comment] 2016-07-25 23:20
Useful info.  It could be the AV or the System Centre Config process (ccmexec.exe) I suppose.

However, what I'm hoping to see are the handles held by RoslynPad?  (rather than RoslynPad handles held by other processes, which is just as useful but is the other side of the coin).

Just hit Ctrl+H in Process Explorer and you'll get a bottom pane as shown below.

![image](https://cloud.githubusercontent.com/assets/1314477/17120718/a311ec58-5311-11e6-9f54-93b46d359487.png)

That'll indicate what handles that stray process still has open and might give @aelij a clue as to what's going on.  The difference between handles held by both RP processes *before* quitting versus *after* is probably of most interest but the full handle list would be interesting in both.

**Comment by modulexcite** [comment] 2016-07-26 12:42
Since the list of handles is quite big, I thought it would more useful if I dumped that information into a text file rather than multiple screen captures. I used the Sysinternals Handles command line tool to get this information.

# RoslynPad.exe Handles List:

- [RP-Handles-BeforeExit.txt](https://github.com/aelij/RoslynPad/files/383817/RP-Handles-BeforeExit.txt)
- [RP-Handles-AfterExit.txt](https://github.com/aelij/RoslynPad/files/383818/RP-Handles-AfterExit.txt)


# RoslynPad.Host32.exe Handles List:

- [RPH32-Handles-BeforeExit.txt](https://github.com/aelij/RoslynPad/files/383820/RPH32-Handles-BeforeExit.txt)
- [RPH32-Handles-AfterExit.txt](https://github.com/aelij/RoslynPad/files/383821/RPH32-Handles-AfterExit.txt)

**Comment by aelij** [comment] 2016-07-28 08:34
Thanks @modulexcite. Unfortunately, I still can't find a reason for the process not terminating.
I was hoping to avoid that, but maybe I'll just add an explicit kill for all child processes when exiting RP.

**Comment by modulexcite** [comment] 2016-07-28 14:41
Thanks a ton for working with me on this @aelij .

Unfortunately, this seems like a problem with Windows 7 machines perhaps it has something to do with how some of the underlying .NET APIs work on Win7 OS compared to Win10. 

I spun up a couple of new VMs for Windows 7 32-bit and 64-bit last night and con confirm that the RPH process lingers around after exiting RP. Just for fun, I've also created a new VM for Windows 10 64-bit and tested on it, it works like its supposed to on this OS. The RPH process exits after closing RP.

I'm assuming you're only testing this on Windows 10 OS and hence you can't replicate the issue. I guess you should put a note somewhere for Windows 7 users if somebody else can confirm this.
Again thanks for the help.

**Comment by TheSLiNKS** [comment] 2016-07-29 06:36
Can confirm the same behaviour what @modulexcite . Windows 7 Pro SP1, Roslyn 0.9 installed.

**Closed** 2016-08-01 06:21 UTC
Labels: bug

**Comment by aelij** [comment] 2016-08-01 06:23
Thanks everyone! I've changed the method of monitoring the processes. Now each child process relies on the `Process.Exited` event of the parent. This should work well under any OS (hopefully). Please let me know if there are any issues.

**Comment by modulexcite** [comment] 2016-08-03 12:28
Thanks @aelij, looking forward to the next release.
