### ISSUE TITLE
Dump Encoding

### ISSUE THREAD

**Issue by mshakurov** [aelij/RoslynPad#287] opened 2019-05-27 18:38 UTC
What happened to the encoding of the strings displayed by the Dump(...) methods?

In the previous version, any encoding lines were displayed correctly.

This is what the command displays:

"**russian language symbols**" .Dump ();

### СЂСѓ Р»СЏ Р»СЏ

**Comment by ttkoma** [comment] 2019-05-27 20:19
In release 14.1 bug.
On latest master build
- no bug.

**Comment by aelij** [comment] 2019-05-28 06:43
Duplicate of #256

**Closed by aelij** 2019-05-28 06:43 UTC
