### ISSUE TITLE
Code that includes typeof operator or calls to GetType never completes execution.

### ISSUE THREAD

**Issue by danysdragons** [aelij/RoslynPad#241] opened 2019-03-15 18:06 UTC
Whenever I've tried to execute C# code that includes use of the _typeof_ operator or a call to _GetType_, the query continues running indefinitely without returning any results. The tiny progress bar beneath the green arrow button at the top left continues indefinitely.

**Examples**:

3.GetType()
// should return [System.Int32], and does in C# Interactive or LINQPad, but query hangs instead

typeof(int)
// should return [System.Int32], and does in C# Interactive or LINQPad, but query hangs instead

"hello".GetType()
// Should return [System.String], and does in C# Interactive or LINQPad, but query hangs instead

I've seen this both in the 13.3 version of RoslynPad, and when building the latest version (as of March 15, 2019) from source.

**Comment by aelij** [comment] 2019-03-16 09:19
Duplicate of #190

**Closed by aelij** 2019-03-16 09:19 UTC
