### ISSUE TITLE
Problems with nuget packages

### ISSUE THREAD

**Issue by LechPa** [aelij/RoslynPad#262] opened 2019-03-28 13:19 UTC
This could be related to:
[Open Build Folder - Location is not available](https://github.com/aelij/RoslynPad/issues/261)

I'm logged in as UserA. I would like to run RoslynPad as Administrator - so when I'm getting a login prompt I'm logging as UserB which has Admin rights.

I have problems with using nuget packages to connect to MS Sql database.

In RoslynPad 13.3 I was using:
#r "$NuGet\System.Data.Common\4.3.0\lib\net451\System.Data.Common.dll"
#r "$NuGet\System.Data.SqlClient\4.6.0\lib\net46\System.Data.SqlClient.dll"

using System.Data.SqlClient;

and I was able to resolve: SqlConnection, ConnectionState, SqlCommand.

When I'm using RoslynPad 14.1 I cannot connect to database - I was trying to resolve this by:
- changing between frameworks: Core x64, Desktopx86, Desktopx64
- picking up different nugets, e.g.
#r "nuget:System.Data.Common/4.3.0"

CS1069: The type name 'SqlConnection' could not be found in the namespace 'System.Data.SqlClient'. This type has been forwarded to assembly 'System.Data.SqlClient, Version=0.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' Consider adding a reference to that assembly.

#r "nuget:System.Data.SqlClient/4.6.0"
#r "nuget:System.Data.Common/4.3.0"

System.DllNotFoundException: Unable to load DLL 'sni.dll' or one of its dependencies: The specified module could not be found. (Exception from HRESULT: 0x8007007E)
   at System.Data.SqlClient.SNINativeMethodWrapper.UnmanagedIsTokenRestricted(IntPtr token, Boolean& isRestricted)
   at System.Data.Win32NativeMethods.IsTokenRestrictedWrapper(IntPtr token)
   at System.Data.ProviderBase.DbConnectionPoolIdentity.GetCurrentNative()
   at System.Data.ProviderBase.DbConnectionPoolGroup.GetConnectionPool(DbConnectionFactory connectionFactory)
   at System.Data.ProviderBase.DbConnectionFactory.GetConnectionPool(DbConnection owningObject, DbConnectionPoolGroup connectionPoolGroup)
   at System.Data.ProviderBase.DbConnectionFactory.TryGetConnection(DbConnection owningConnection, TaskCompletionSource`1 retry, DbConnectionOptions userOptions, DbConnectionInternal oldConnection, DbConnectionInternal& connection)
   at System.Data.ProviderBase.DbConnectionInternal.TryOpenConnectionInternal(DbConnection outerConnection, DbConnectionFactory connectionFactory, TaskCompletionSource`1 retry, DbConnectionOptions userOptions)
   at System.Data.SqlClient.SqlConnection.TryOpen(TaskCompletionSource`1 retry)
   at System.Data.SqlClient.SqlConnection.Open()
   at Program.FixGenerator.GetUpdateQuery(Int32 auditLogId) in :line 45

**Comment by TuyenTk** [comment] 2019-03-28 13:50
Seem this is same with #257 which is already fixed.

**Comment by aelij** [comment] 2019-03-30 05:10
Can you please share the generated deps.json file? You can find it by clicking the folder button on the toolbar.

**Comment by aelij** [comment] 2019-03-30 06:06
Both the old style references and new style references work on my machine. I was able to create a `SqlConnection` from a session with a different user.

Can you try using `runas` to start RoslynPad? e.g. `runas /user:<your-user> RoslynPad.exe`

**Comment by LechPa** [comment] 2019-03-30 12:03
Thank you for an answer. I'm not using `runas`, I've checked `Run as Administrator` setting of RP executable - this is the reason of running RP as a different user.
I will share the file and run some test on Monday (I have this on my work machine)

**Comment by LechPa** [comment] 2019-04-01 06:07
[temp.deps.zip](https://github.com/aelij/RoslynPad/files/3027935/temp.deps.zip)

When I was trying to runas UserB:

Attempting to start RoslynPad.exe as user "UserB" ...
RUNAS ERROR: Unable to run - RoslynPad.exe
5: Access is denied.

**Comment by aelij** [comment] 2019-07-05 08:39
Duplicate of #261

**Closed by aelij** 2019-07-05 08:39 UTC
