### ISSUE TITLE
C# 9 records do not work

### ISSUE THREAD

**Issue by mikernet** [aelij/RoslynPad#374] opened 2020-11-13 10:27 UTC
**Describe the bug**

C# 9 records do not work with .NET 5 release version. I'm not 100% certain if this is a `RoslynPad` issue or a CSX issue.

Attempting to use a record with a parameter results in:

> CS0518: Predefined type 'System.Runtime.CompilerServices.IsExternalInit' is not defined or imported

![image](https://user-images.githubusercontent.com/1700111/99062163-8ef64080-2570-11eb-8d54-0b08c57d9633.png)

It does not appear possible to add it manually since namespaces are not supported.

**To Reproduce**

Try the following code:

```cs
record SomeRecordType(string Name);
```

**Expected behavior**

Compiles OK.

**Version**
- OS: Win 10
- Build: v15.1

**Comment by aelij** [comment] 2020-11-13 10:37
Duplicate of #373

**Closed by aelij** 2020-11-13 10:37 UTC

**Comment by mikernet** [comment] 2020-11-13 21:20
Oh what the heck....I searched for it...

Ah, it's a screenshot, so "IsExternalInit" didn't bring up any results...and the title says "record" not "records" so it didn't come up when I searched the latter either. 

Oopsies, by bad :)
