### ISSUE TITLE
C# Editor or C# SCRIPT editor?

### ISSUE THREAD

**Issue by rerdavies** [aelij/RoslynPad#341] opened 2020-05-15 22:08 UTC
Seems to be an editor for C#Script. I wanted a C# editor. Is there any way to flip the behavior? If not, could you please rename the project accordingly to reflect that this a script editor not a c# editor. Thx.

**Comment by aelij** [comment] 2020-05-16 06:46
Duplicate of #150

**Closed by aelij** 2020-05-16 06:46 UTC
