### ISSUE TITLE
Turkish/Unicode character problem in results pane

### ISSUE THREAD

**Issue by buraktuncbilek** [aelij/RoslynPad#289] opened 2019-06-24 10:50 UTC
Results pane are not support unicode characters. 
for example see below
![resim](https://user-images.githubusercontent.com/29338175/60013240-a3d5e980-9686-11e9-90b2-0b0d7e61c784.png)

**Comment by aelij** [comment] 2019-06-26 08:18
Duplicate of #256

**Closed by aelij** 2019-06-26 08:18 UTC
