### ISSUE TITLE
Console.WriteLine from a loop not outputting all values

### ISSUE THREAD

**Issue by MarqueIV** [aelij/RoslynPad#297] opened 2019-08-03 17:47 UTC
There's an issue with reporting the output of RoslynPad.  Try this code...

```
for(var i = 1; i <= 10; i++)
    Console.WriteLine(i);
```

Run it a few times and you will see it only output the first three, the first two, the first five, etc.  It rarely shows all output.

However, when you add a final `Console.WriteLine()` after the loop, you then see all output.

```
for(var i = 1; i <= 10; i++)
    Console.WriteLine(i);
    
Console.WriteLine("Done");
```

My guess is whatever is capturing the output is being released before all the output is actually generated, but this is pure speculation as I haven't 'dug in' to the RoslynPad code yet.

**Comment by aelij** [comment] 2019-08-03 17:51
Duplicate of #253

**Closed by aelij** 2019-08-03 17:51 UTC
